[package]
name = "bevy_particle_systems"
version = "0.6.0-dev"
edition = "2021"
rust-version = "1.59"
authors = ["Abnormal Brain Studios"]
license = "MIT"
description = "A particle system plugin for Bevy"
repository = "https://github.com/abnormalbrain/bevy_particle_systems"
keywords = ["game", "gamedev", "bevy"]
categories = ["game-development"]

[dependencies]
rand = "0.8"

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy.git"
rev = "543465b721048355e34eb6078923645747c1d44b"

default-features=false
features = ["bevy_asset", "render", "png", "bevy_winit", "x11"]